### PR TITLE
WIP: Add Pipeline model and AIP dashboard URL link to AIPscan

### PR DESCRIPTION
**Pull request by tw4l**
Connected to #136

This PR adds a new `Pipeline` model with fields `origin_pipeline` and `dashboard_url` that is connected to the `Storage Service` and `AIP` models via foreign key. It also adds a link to the origin dashboard on the AIP detail page:

image

Updated ERD:

relationships real large

This needs to be rebased on main after https://github.com/artefactual-labs/AIPscan/pull/134 is merged.

### CODE REVIEW

**Review by peterVG — APPROVED** [review]
LGTM and all updated tests pass.

**Comment by peterVG** [comment]
Also these ER diagrams have made these enhancements very easy to follow!

**Comment by tw4l** [comment]
Thanks @peterVG, and I'm glad the ERD diagrams helped! I'll update the associated issue after merging this.

**Comment by tw4l** [comment]
Updated PR against main: https://github.com/artefactual-labs/AIPscan/pull/148

**Pull request closed without merging**
