### PR TITLE
Add full stop to all report descriptions

### PR DESCRIPTION
**Pull request by peterVG**

### CODE REVIEW

**Review by tw4l — CHANGES_REQUESTED** [review]
Thanks @peterVG. This needs a few changes before it's ready to be merged:

1. This branch needs to be rebased on `main`, both for a clean merge but also to help with code review, so that we're only looking at the latest changes and not what's already been merged in another PR.
2. "Filter by date range." should be added in the Description for the Storage locations report.
3. In Largest files, the in-report filter is described with "(in report)" and in a separate sentence. In Preservation derivatives, it's described with "(inside report)" and in the same sentence. It'd be great to have them both say "(in report)" and have the in-report filter mentioned in a separate sentence for consistency.
4. The button for the AIP Contents report appears to be broken (it appears to have been broken when the last PR was merged - my guess is that its ID was changed but was reverted when resolving merge conflicts).

**Comment by peterVG** [comment]
> This branch needs to be rebased on main, both for a clean merge but also to help with code review, so that we're only looking at the latest changes and not what's already been merged in another PR.

> git checkout main
git pull --rebase
git checkout dev-branch
git rebase main
(resolve conflicts in editor, git add file/with/conflict, git rebase --continue)
git push -f origin dev-branch

Done. Thanks very much for instructions. Copying here for future reference.

> "Filter by date range." should be added in the Description for the Storage locations report.

Nice this feature keeps getting better. Done.

> In Largest files, the in-report filter is described with "(in report)" and in a separate sentence. In Preservation derivatives, it's described with "(inside report)" and in the same sentence. It'd be great to have them both say "(in report)" and have the in-report filter mentioned in a separate sentence for consistency.

Yes! I remember seeing this after I did the commit but it was late and I was tired. This is why we do peer review :-) Thanks for catching this it would have bugged me. Fixed now.

> The button for the AIP Contents report appears to be broken (it appears to have been broken when the last PR was merged - my guess is that its ID was changed but was reverted when resolving merge conflicts).

Whoa! how did you catch this? Did you hit all the buttons as a QA step? You have so little faith in our code? :-) But yeah,  not working on my end anymore either. Will troubleshoot tonight...

**Comment by peterVG** [comment]
Aaand, you we're right, again @tw4l The button's ID got changed so Jquery function wasn't getting triggered. I fixed that in last commit which takes care of last PR feedback issue.

**Review by tw4l — APPROVED** [review]
Nice work @peterVG - this looks great and is ready to merge! :tada: 

> Whoa! how did you catch this? Did you hit all the buttons as a QA step? You have so little faith in our code? :-) But yeah, not working on my end anymore either. Will troubleshoot tonight...

I prefer to think of it as an abundance of caution :wink:

**Comment by peterVG** [comment]
Just realized I'm *still* not following basic commit rule: Capitalize, no period

**Pull request merged**
