### PR TITLE
WIP: Add fileGrp USE="Derivative" handling to fetch

### PR DESCRIPTION
**Pull request by ross-spencer**
Fetch jobs were not successfully picking up the derivative type which
is used by Dataverse transfers. We add that here.

Connected to artefactual-labs/aipscan#52

### CODE REVIEW

**Comment by ross-spencer** [comment]
@peterVG @tw4l what do you think about this fileGrp handling in AIPscan. The derivative type expresses a relationship between a tabular format in Dataverse and the concept of a Bundle which is described in the [Wiki](https://wiki.archivematica.org/Dataverse#Bundles_for_tabular_data_files). (Tessa, you probably have more institutional knowledge of this!) 

We noticed the original-derivatives report wasn't being written out correctly. While I happened to use derivative as the term in that report, the other parts of AIPscan are focused on either originals or preservation copies:

image

image

So, that leads me to ask, what is the full extent of the change I might make for AIPscan to handle derivatives properly. Largely, they are in the camp of:

1. Treat them as unique, and update the screens (and maybe add a derivative type to the report). 
2. Treat them as originals, and leave the screens the same, and don't talk about them separately. 
3. ~~Treat them as preservation copies~~ (As ever putting all options out there, this one doesn't feel correct).
4. Something else?

**Comment by ross-spencer** [comment]
Ah! Just going to read this Tessa! https://github.com/artefactual-labs/AIPscan/issues/55 (which seems timely!)

**Comment by tw4l** [comment]
@ross-spencer It's an interesting question!

Are these Dataverse derivatives unique in the respect of being derivatives that are not necessarily preservation derivatives and were created in advance of ingest into Archivematica? It seems that the choice to use fileGrp="derivative" signifies an intent not to think of them in Archivematica as original files or preservation copes (I agree with you that the latter seems particularly not right).

I'm wavering between 1 and 2, and might suggest a slightly hybrid approach:

- Store them in the database as a distinct type of file (maybe type="dataverse_derivative" or type="derivative", to tie it to my suggestions in #55) to retain granularity of the data.
-Decide whether to treat them as originals or as distinct on a per-report basis. This might be where some user stories would really help us out. If as an administrator looking for reports my intention is to separate out the files Archivematica received from the files Archivematica created, I could see a use case for considering the Dataverse derivatives as an original file in some cases. In some other cases, it might make sense to view them separately.

**Comment by tw4l** [comment]
Closing due to inactivity and because this branch has drifted from main.

**Pull request closed without merging**
