### PR TITLE
Add Storage Locations to AIPscan

### PR DESCRIPTION
**Pull request by tw4l**
Connected to #87 

This PR introduces a new `StorageLocation` model to AIPscan, which models an AIP storage location. Aggregator tasks are modified to write Storage Locations to the database and associate them with each AIP. All existing `Data` endpoints and reports are updated to include an option to filter by storage location, and the reports UI and individual reports are updated accordingly. Finally, a new "AIP storage locations" report is introduced which takes a Storage Service as input and lists details for each AIP store location, sorted descending by AIP count:

image

I've also taken the opportunity to do a bit of additional code cleanup as I went, fixing minor issues as I saw them.

Screenshot of updated reports UI (the Storage Service and Location dropdown filters are identical on the AIPs page):

image

New database ERD as of this work (I will update the associated issue after this is merged):

image

### CODE REVIEW

**Comment by tw4l** [comment]
Hi @peterVG - this is now ready for review.

**Comment by tw4l** [comment]
I've made an addition to add support for date range filtering on the Storage Service location report, using the AIP creation dates. This isn't a perfect metric but is consistent with how we're treating it in the rest of the AIPscan application so I think it makes sense given the client demand.

This is now ready for review @peterVG - thanks!

**Comment by tw4l** [comment]
The latest commit better aligns the parameter selectors at the top of the Reports page, as per the now-closed https://github.com/artefactual-labs/AIPscan/issues/140: 

image

**Comment by peterVG** [comment]
Date range filtering addition works well.

**Review by peterVG — APPROVED** [review]
Code is consistent and easy to read. Thanks for updating all the tests. They all pass in my env too.

**Pull request merged**
